export const SELLER_PRODUCT_LIST_REQUEST = 'SELLER_PRODUCT_LIST_REQUEST';
export const SELLER_PRODUCT_LIST_SUCCESS = 'SELLER_PRODUCT_LIST_SUCCESS';
export const SELLER_PRODUCT_LIST_FAIL = 'SELLER_PRODUCT_LIST_FAIL';

export const SELLER_PRODUCT_DETAILS_REQUEST = 'SELLER_PRODUCT_DETAILS_REQUEST';
export const SELLER_PRODUCT_DETAILS_SUCCESS = 'SELLER_PRODUCT_DETAILS_SUCCESS';
export const SELLER_PRODUCT_DETAILS_FAIL = 'SELLER_PRODUCT_DETAILS_FAIL';

export const SELLER_PRODUCT_SAVE_REQUEST = 'SELLER_PRODUCT_SAVE_REQUEST';
export const SELLER_PRODUCT_SAVE_SUCCESS = 'SELLER_PRODUCT_SAVE_SUCCESS';
export const SELLER_PRODUCT_SAVE_FAIL = 'SELLER_PRODUCT_SAVE_FAIL';

export const SELLER_PRODUCT_DELETE_REQUEST = 'SELLER_PRODUCT_DELETE_REQUEST';
export const SELLER_PRODUCT_DELETE_SUCCESS = 'SELLER_PRODUCT_DELETE_SUCCESS';
export const SELLER_PRODUCT_DELETE_FAIL = 'SELLER_PRODUCT_DELETE_FAIL';